steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase', '-f', 'Dockerfile.firebase', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/make', '-f', 'Dockerfile.make', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sassc', '-f', 'Dockerfile.sassc', '.']
images:
- 'gcr.io/$PROJECT_ID/firebase'
- 'gcr.io/$PROJECT_ID/make'
- 'gcr.io/$PROJECT_ID/sassc'
